// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"github.com/Peanuttown/dd_contacts/ent/dept"
	"github.com/Peanuttown/dd_contacts/ent/schema"
	"github.com/Peanuttown/dd_contacts/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deptHooks := schema.Dept{}.Hooks()
	dept.Hooks[0] = deptHooks[0]
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
}

const (
	Version = "v0.8.0"                                          // Version of ent codegen.
	Sum     = "h1:xirrW//1oda7pp0bz+XssSOv4/C3nmgYQOxjIfljFt8=" // Sum of ent codegen.
)
