// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Peanuttown/dd_contacts/ent/dept"
	"github.com/Peanuttown/dd_contacts/ent/predicate"
	"github.com/Peanuttown/dd_contacts/ent/user"
	"github.com/Peanuttown/dd_contacts/ent/userpropertyindept"
)

// UserPropertyInDeptQuery is the builder for querying UserPropertyInDept entities.
type UserPropertyInDeptQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserPropertyInDept
	// eager-loading edges.
	withUser *UserQuery
	withDept *DeptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserPropertyInDeptQuery builder.
func (upidq *UserPropertyInDeptQuery) Where(ps ...predicate.UserPropertyInDept) *UserPropertyInDeptQuery {
	upidq.predicates = append(upidq.predicates, ps...)
	return upidq
}

// Limit adds a limit step to the query.
func (upidq *UserPropertyInDeptQuery) Limit(limit int) *UserPropertyInDeptQuery {
	upidq.limit = &limit
	return upidq
}

// Offset adds an offset step to the query.
func (upidq *UserPropertyInDeptQuery) Offset(offset int) *UserPropertyInDeptQuery {
	upidq.offset = &offset
	return upidq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upidq *UserPropertyInDeptQuery) Unique(unique bool) *UserPropertyInDeptQuery {
	upidq.unique = &unique
	return upidq
}

// Order adds an order step to the query.
func (upidq *UserPropertyInDeptQuery) Order(o ...OrderFunc) *UserPropertyInDeptQuery {
	upidq.order = append(upidq.order, o...)
	return upidq
}

// QueryUser chains the current query on the "user" edge.
func (upidq *UserPropertyInDeptQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: upidq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := upidq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := upidq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userpropertyindept.Table, userpropertyindept.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userpropertyindept.UserTable, userpropertyindept.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(upidq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDept chains the current query on the "dept" edge.
func (upidq *UserPropertyInDeptQuery) QueryDept() *DeptQuery {
	query := &DeptQuery{config: upidq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := upidq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := upidq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userpropertyindept.Table, userpropertyindept.FieldID, selector),
			sqlgraph.To(dept.Table, dept.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userpropertyindept.DeptTable, userpropertyindept.DeptColumn),
		)
		fromU = sqlgraph.SetNeighbors(upidq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserPropertyInDept entity from the query.
// Returns a *NotFoundError when no UserPropertyInDept was found.
func (upidq *UserPropertyInDeptQuery) First(ctx context.Context) (*UserPropertyInDept, error) {
	nodes, err := upidq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userpropertyindept.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) FirstX(ctx context.Context) *UserPropertyInDept {
	node, err := upidq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserPropertyInDept ID from the query.
// Returns a *NotFoundError when no UserPropertyInDept ID was found.
func (upidq *UserPropertyInDeptQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = upidq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userpropertyindept.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) FirstIDX(ctx context.Context) int {
	id, err := upidq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserPropertyInDept entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserPropertyInDept entity is not found.
// Returns a *NotFoundError when no UserPropertyInDept entities are found.
func (upidq *UserPropertyInDeptQuery) Only(ctx context.Context) (*UserPropertyInDept, error) {
	nodes, err := upidq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userpropertyindept.Label}
	default:
		return nil, &NotSingularError{userpropertyindept.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) OnlyX(ctx context.Context) *UserPropertyInDept {
	node, err := upidq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserPropertyInDept ID in the query.
// Returns a *NotSingularError when exactly one UserPropertyInDept ID is not found.
// Returns a *NotFoundError when no entities are found.
func (upidq *UserPropertyInDeptQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = upidq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = &NotSingularError{userpropertyindept.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) OnlyIDX(ctx context.Context) int {
	id, err := upidq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserPropertyInDepts.
func (upidq *UserPropertyInDeptQuery) All(ctx context.Context) ([]*UserPropertyInDept, error) {
	if err := upidq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return upidq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) AllX(ctx context.Context) []*UserPropertyInDept {
	nodes, err := upidq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserPropertyInDept IDs.
func (upidq *UserPropertyInDeptQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := upidq.Select(userpropertyindept.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) IDsX(ctx context.Context) []int {
	ids, err := upidq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upidq *UserPropertyInDeptQuery) Count(ctx context.Context) (int, error) {
	if err := upidq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return upidq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) CountX(ctx context.Context) int {
	count, err := upidq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upidq *UserPropertyInDeptQuery) Exist(ctx context.Context) (bool, error) {
	if err := upidq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return upidq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (upidq *UserPropertyInDeptQuery) ExistX(ctx context.Context) bool {
	exist, err := upidq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserPropertyInDeptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upidq *UserPropertyInDeptQuery) Clone() *UserPropertyInDeptQuery {
	if upidq == nil {
		return nil
	}
	return &UserPropertyInDeptQuery{
		config:     upidq.config,
		limit:      upidq.limit,
		offset:     upidq.offset,
		order:      append([]OrderFunc{}, upidq.order...),
		predicates: append([]predicate.UserPropertyInDept{}, upidq.predicates...),
		withUser:   upidq.withUser.Clone(),
		withDept:   upidq.withDept.Clone(),
		// clone intermediate query.
		sql:  upidq.sql.Clone(),
		path: upidq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (upidq *UserPropertyInDeptQuery) WithUser(opts ...func(*UserQuery)) *UserPropertyInDeptQuery {
	query := &UserQuery{config: upidq.config}
	for _, opt := range opts {
		opt(query)
	}
	upidq.withUser = query
	return upidq
}

// WithDept tells the query-builder to eager-load the nodes that are connected to
// the "dept" edge. The optional arguments are used to configure the query builder of the edge.
func (upidq *UserPropertyInDeptQuery) WithDept(opts ...func(*DeptQuery)) *UserPropertyInDeptQuery {
	query := &DeptQuery{config: upidq.config}
	for _, opt := range opts {
		opt(query)
	}
	upidq.withDept = query
	return upidq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserPropertyInDept.Query().
//		GroupBy(userpropertyindept.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (upidq *UserPropertyInDeptQuery) GroupBy(field string, fields ...string) *UserPropertyInDeptGroupBy {
	group := &UserPropertyInDeptGroupBy{config: upidq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := upidq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return upidq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.UserPropertyInDept.Query().
//		Select(userpropertyindept.FieldUserID).
//		Scan(ctx, &v)
//
func (upidq *UserPropertyInDeptQuery) Select(field string, fields ...string) *UserPropertyInDeptSelect {
	upidq.fields = append([]string{field}, fields...)
	return &UserPropertyInDeptSelect{UserPropertyInDeptQuery: upidq}
}

func (upidq *UserPropertyInDeptQuery) prepareQuery(ctx context.Context) error {
	for _, f := range upidq.fields {
		if !userpropertyindept.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upidq.path != nil {
		prev, err := upidq.path(ctx)
		if err != nil {
			return err
		}
		upidq.sql = prev
	}
	return nil
}

func (upidq *UserPropertyInDeptQuery) sqlAll(ctx context.Context) ([]*UserPropertyInDept, error) {
	var (
		nodes       = []*UserPropertyInDept{}
		_spec       = upidq.querySpec()
		loadedTypes = [2]bool{
			upidq.withUser != nil,
			upidq.withDept != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserPropertyInDept{config: upidq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, upidq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := upidq.withUser; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*UserPropertyInDept)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	if query := upidq.withDept; query != nil {
		ids := make([]uint, 0, len(nodes))
		nodeids := make(map[uint][]*UserPropertyInDept)
		for i := range nodes {
			fk := nodes[i].DeptID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(dept.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "dept_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Dept = n
			}
		}
	}

	return nodes, nil
}

func (upidq *UserPropertyInDeptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upidq.querySpec()
	return sqlgraph.CountNodes(ctx, upidq.driver, _spec)
}

func (upidq *UserPropertyInDeptQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := upidq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (upidq *UserPropertyInDeptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userpropertyindept.Table,
			Columns: userpropertyindept.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userpropertyindept.FieldID,
			},
		},
		From:   upidq.sql,
		Unique: true,
	}
	if unique := upidq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := upidq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpropertyindept.FieldID)
		for i := range fields {
			if fields[i] != userpropertyindept.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upidq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upidq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upidq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upidq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upidq *UserPropertyInDeptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upidq.driver.Dialect())
	t1 := builder.Table(userpropertyindept.Table)
	selector := builder.Select(t1.Columns(userpropertyindept.Columns...)...).From(t1)
	if upidq.sql != nil {
		selector = upidq.sql
		selector.Select(selector.Columns(userpropertyindept.Columns...)...)
	}
	for _, p := range upidq.predicates {
		p(selector)
	}
	for _, p := range upidq.order {
		p(selector)
	}
	if offset := upidq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upidq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserPropertyInDeptGroupBy is the group-by builder for UserPropertyInDept entities.
type UserPropertyInDeptGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upidgb *UserPropertyInDeptGroupBy) Aggregate(fns ...AggregateFunc) *UserPropertyInDeptGroupBy {
	upidgb.fns = append(upidgb.fns, fns...)
	return upidgb
}

// Scan applies the group-by query and scans the result into the given value.
func (upidgb *UserPropertyInDeptGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := upidgb.path(ctx)
	if err != nil {
		return err
	}
	upidgb.sql = query
	return upidgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := upidgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(upidgb.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := upidgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) StringsX(ctx context.Context) []string {
	v, err := upidgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upidgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) StringX(ctx context.Context) string {
	v, err := upidgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(upidgb.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := upidgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) IntsX(ctx context.Context) []int {
	v, err := upidgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upidgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) IntX(ctx context.Context) int {
	v, err := upidgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(upidgb.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := upidgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := upidgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upidgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) Float64X(ctx context.Context) float64 {
	v, err := upidgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(upidgb.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := upidgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := upidgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upidgb *UserPropertyInDeptGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upidgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upidgb *UserPropertyInDeptGroupBy) BoolX(ctx context.Context) bool {
	v, err := upidgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upidgb *UserPropertyInDeptGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range upidgb.fields {
		if !userpropertyindept.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := upidgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upidgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upidgb *UserPropertyInDeptGroupBy) sqlQuery() *sql.Selector {
	selector := upidgb.sql
	columns := make([]string, 0, len(upidgb.fields)+len(upidgb.fns))
	columns = append(columns, upidgb.fields...)
	for _, fn := range upidgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(upidgb.fields...)
}

// UserPropertyInDeptSelect is the builder for selecting fields of UserPropertyInDept entities.
type UserPropertyInDeptSelect struct {
	*UserPropertyInDeptQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (upids *UserPropertyInDeptSelect) Scan(ctx context.Context, v interface{}) error {
	if err := upids.prepareQuery(ctx); err != nil {
		return err
	}
	upids.sql = upids.UserPropertyInDeptQuery.sqlQuery(ctx)
	return upids.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) ScanX(ctx context.Context, v interface{}) {
	if err := upids.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Strings(ctx context.Context) ([]string, error) {
	if len(upids.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := upids.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) StringsX(ctx context.Context) []string {
	v, err := upids.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upids.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) StringX(ctx context.Context) string {
	v, err := upids.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Ints(ctx context.Context) ([]int, error) {
	if len(upids.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := upids.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) IntsX(ctx context.Context) []int {
	v, err := upids.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upids.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) IntX(ctx context.Context) int {
	v, err := upids.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(upids.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := upids.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) Float64sX(ctx context.Context) []float64 {
	v, err := upids.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upids.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) Float64X(ctx context.Context) float64 {
	v, err := upids.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(upids.fields) > 1 {
		return nil, errors.New("ent: UserPropertyInDeptSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := upids.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) BoolsX(ctx context.Context) []bool {
	v, err := upids.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (upids *UserPropertyInDeptSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upids.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userpropertyindept.Label}
	default:
		err = fmt.Errorf("ent: UserPropertyInDeptSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upids *UserPropertyInDeptSelect) BoolX(ctx context.Context) bool {
	v, err := upids.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upids *UserPropertyInDeptSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := upids.sqlQuery().Query()
	if err := upids.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upids *UserPropertyInDeptSelect) sqlQuery() sql.Querier {
	selector := upids.sql
	selector.Select(selector.Columns(upids.fields...)...)
	return selector
}
