// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Peanuttown/dd_contacts/ent/predicate"
	"github.com/Peanuttown/dd_contacts/ent/userpropertyindept"
)

// UserPropertyInDeptDelete is the builder for deleting a UserPropertyInDept entity.
type UserPropertyInDeptDelete struct {
	config
	hooks    []Hook
	mutation *UserPropertyInDeptMutation
}

// Where adds a new predicate to the UserPropertyInDeptDelete builder.
func (upidd *UserPropertyInDeptDelete) Where(ps ...predicate.UserPropertyInDept) *UserPropertyInDeptDelete {
	upidd.mutation.predicates = append(upidd.mutation.predicates, ps...)
	return upidd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (upidd *UserPropertyInDeptDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(upidd.hooks) == 0 {
		affected, err = upidd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserPropertyInDeptMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			upidd.mutation = mutation
			affected, err = upidd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(upidd.hooks) - 1; i >= 0; i-- {
			mut = upidd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, upidd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (upidd *UserPropertyInDeptDelete) ExecX(ctx context.Context) int {
	n, err := upidd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (upidd *UserPropertyInDeptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userpropertyindept.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userpropertyindept.FieldID,
			},
		},
	}
	if ps := upidd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, upidd.driver, _spec)
}

// UserPropertyInDeptDeleteOne is the builder for deleting a single UserPropertyInDept entity.
type UserPropertyInDeptDeleteOne struct {
	upidd *UserPropertyInDeptDelete
}

// Exec executes the deletion query.
func (upiddo *UserPropertyInDeptDeleteOne) Exec(ctx context.Context) error {
	n, err := upiddo.upidd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpropertyindept.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (upiddo *UserPropertyInDeptDeleteOne) ExecX(ctx context.Context) {
	upiddo.upidd.ExecX(ctx)
}
