// Code generated by entc, DO NOT EDIT.

package userpropertyindept

const (
	// Label holds the string label denoting the userpropertyindept type in the database.
	Label = "user_property_in_dept"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeptID holds the string denoting the dept_id field in the database.
	FieldDeptID = "dept_id"
	// FieldIsLeader holds the string denoting the isleader field in the database.
	FieldIsLeader = "is_leader"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDept holds the string denoting the dept edge name in mutations.
	EdgeDept = "dept"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "user_id"
	// DeptFieldID holds the string denoting the ID field of the Dept.
	DeptFieldID = "dept_id"
	// Table holds the table name of the userpropertyindept in the database.
	Table = "user_property_in_depts"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "user_property_in_depts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// DeptTable is the table the holds the dept relation/edge.
	DeptTable = "user_property_in_depts"
	// DeptInverseTable is the table name for the Dept entity.
	// It exists in this package in order to avoid circular dependency with the "dept" package.
	DeptInverseTable = "depts"
	// DeptColumn is the table column denoting the dept relation/edge.
	DeptColumn = "dept_id"
)

// Columns holds all SQL columns for userpropertyindept fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDeptID,
	FieldIsLeader,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
