// Code generated by entc, DO NOT EDIT.

package user

import (
	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// EdgeDepts holds the string denoting the depts edge name in mutations.
	EdgeDepts = "depts"
	// EdgePropertiesInDept holds the string denoting the properties_in_dept edge name in mutations.
	EdgePropertiesInDept = "properties_in_dept"
	// DeptFieldID holds the string denoting the ID field of the Dept.
	DeptFieldID = "dept_id"
	// UserPropertyInDeptFieldID holds the string denoting the ID field of the UserPropertyInDept.
	UserPropertyInDeptFieldID = "id"
	// Table holds the table name of the user in the database.
	Table = "users"
	// DeptsTable is the table the holds the depts relation/edge. The primary key declared below.
	DeptsTable = "dept_users"
	// DeptsInverseTable is the table name for the Dept entity.
	// It exists in this package in order to avoid circular dependency with the "dept" package.
	DeptsInverseTable = "depts"
	// PropertiesInDeptTable is the table the holds the properties_in_dept relation/edge.
	PropertiesInDeptTable = "user_property_in_depts"
	// PropertiesInDeptInverseTable is the table name for the UserPropertyInDept entity.
	// It exists in this package in order to avoid circular dependency with the "userpropertyindept" package.
	PropertiesInDeptInverseTable = "user_property_in_depts"
	// PropertiesInDeptColumn is the table column denoting the properties_in_dept relation/edge.
	PropertiesInDeptColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhone,
	FieldGeneration,
}

var (
	// DeptsPrimaryKey and DeptsColumn2 are the table columns denoting the
	// primary key for the depts relation (M2M).
	DeptsPrimaryKey = []string{"dept_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Peanuttown/dd_contacts/ent/runtime"
//
var (
	Hooks [1]ent.Hook
)
