// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dept is the predicate function for dept builders.
type Dept func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPropertyInDept is the predicate function for userpropertyindept builders.
type UserPropertyInDept func(*sql.Selector)
